baseURL = 'https://blog.hubianluanma.com'
languageCode = 'zh-CN'
hasCJKLanguage = true
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = false
title = '胡编乱码'
theme = 'mainroad'
[Params.logo]
  image = false
  title = "胡编乱码"
  subtitle = "用有趣的方式讲述编码的世界"
[Params.style.vars]
  highlightColor = "#2c3e50"
[Params.sidebar]
  home = "right"
  list = "right"
  single = "right"
  widgets = ["recent", "categories", "taglist", "social"]
[Params.widgets.social]
  cached = true
  twitter = "huhailong1121"
  instagram = "huhailong1121"
  github = "hubianluanma"
  email = "huhailong1121@gmail.com"
[[Params.widgets.social.custom]]
  title = "huhailong"
  url = "https://www.huhailong.vip"
[Params.widgets.search]
  cached = true
[Params.widgets.recent]
  cached = true
[Params.widgets.categories]
  cached = true
[Params.widgets.taglist]
  cached = true
[Params.widgets.languages]
  cached = true
[caches]
  [caches.images]
    dir = ':cacheDir/images'
